# models/silver/schema.yml

version: 2

models:
  - name: users_new
    description: "The cleaned and standardized user data ready for downstream analysis."
    
    columns:

      - name: id
        description: "The standardized, unique integer identifier for the user."
        tests:
          - unique
          - not_null

      # 2. Standardized Names - Must be non-null after cleaning
      - name: first_name
        description: "Standardized first name (e.g., trimmed, title-cased)."
        tests:
          - not_null
          
  - name: anomalies_log
    description: "A log table containing user IDs and diagnostic flags for records that were deemed anomalous and remediated (status set to 'cancelled') in the users_new table."
    config:
      schema: reports # Optional: materializes in a separate 'reports' schema
    
    columns:
      - name: anomalous_user_id
        description: "The primary key of the record that was flagged as anomalous."
        tests:
          - not_null

      - name: remediation_action
        description: "Description of the automated action taken (e.g., status cancellation)."
      # ... (document all flag columns as inherited from the Bronze layer)
